/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theater.app;

/**
 *
 * @author S.Ragawender
 */
public class FinalTransaction extends javax.swing.JFrame {

    /**
     * Creates new form FinalTransaction
     */
    public FinalTransaction() {
        initComponents();
    }
    //overloaded constructor
    public FinalTransaction(String film,String time,String seats, String amount){
        initComponents();
        lblMoveiName.setText(film);
        lblMovieTime.setText(time);
        lblSeats.setText(seats);
        lblTotal.setText(amount);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMoveiName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMovieTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(158, 34, 4));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("MOVIE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 90, 124, 31);

        lblMoveiName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMoveiName.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lblMoveiName);
        lblMoveiName.setBounds(270, 90, 155, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("TIME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 140, 124, 28);

        lblMovieTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMovieTime.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lblMovieTime);
        lblMovieTime.setBounds(270, 140, 155, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("SEATS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 190, 124, 29);

        lblSeats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lblSeats);
        lblSeats.setBounds(270, 190, 155, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("TOTAL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 240, 124, 24);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lblTotal);
        lblTotal.setBounds(270, 240, 155, 24);

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfirm.setText("OK");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm);
        btnConfirm.setBounds(310, 330, 119, 38);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 204));
        jLabel9.setText(" Your Ticket(s) are Confirmed");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 10, 280, 34);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        //Calling main window
        MovieSelection movieSelection = new MovieSelection();
        movieSelection.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMoveiName;
    private javax.swing.JLabel lblMovieTime;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
