/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theater.app;

/**
 *
 * @author S.Ragawender
 */
public class MovieSelection extends javax.swing.JFrame {
    //Names of Movies
    public String movieD1S1="Inception";
    public String movieD1S2="Oblivion";
    public String movieD2S1="Intersteller";
    public String movieD2S2="Upside Down";
    public String movieD3S1="Joker";
    public String movieD3S2="Inception";
    public String movieD4S1="Oblivion";
    public String movieD4S2="Joker";
    public String movieD5S1="Upside Down";
    public String movieD5S2="Intersteller";

    /**
     * Creates new form MovieSelection
     */
    public MovieSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        day1Show1 = new javax.swing.JButton();
        day2Show1 = new javax.swing.JButton();
        day5Show1 = new javax.swing.JButton();
        day3Show1 = new javax.swing.JButton();
        day4Show1 = new javax.swing.JButton();
        day2Show2 = new javax.swing.JButton();
        day1Show2 = new javax.swing.JButton();
        day5Show2 = new javax.swing.JButton();
        day3Show2 = new javax.swing.JButton();
        day4Show2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        day1Show1.setText("Book");
        day1Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(day1Show1);
        day1Show1.setBounds(110, 380, 117, 35);

        day2Show1.setText("Book");
        day2Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(day2Show1);
        day2Show1.setBounds(390, 380, 117, 35);

        day5Show1.setText("Book");
        day5Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day5Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(day5Show1);
        day5Show1.setBounds(1190, 380, 127, 35);

        day3Show1.setText("Book");
        day3Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(day3Show1);
        day3Show1.setBounds(650, 380, 117, 35);

        day4Show1.setText("Book");
        day4Show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day4Show1ActionPerformed(evt);
            }
        });
        getContentPane().add(day4Show1);
        day4Show1.setBounds(930, 380, 117, 35);

        day2Show2.setText("Book");
        day2Show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2Show2ActionPerformed(evt);
            }
        });
        getContentPane().add(day2Show2);
        day2Show2.setBounds(370, 700, 117, 35);

        day1Show2.setText("Book");
        day1Show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1Show2ActionPerformed(evt);
            }
        });
        getContentPane().add(day1Show2);
        day1Show2.setBounds(110, 700, 117, 35);

        day5Show2.setText("Book");
        day5Show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day5Show2ActionPerformed(evt);
            }
        });
        getContentPane().add(day5Show2);
        day5Show2.setBounds(1180, 700, 127, 35);

        day3Show2.setText("Book");
        day3Show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3Show2ActionPerformed(evt);
            }
        });
        getContentPane().add(day3Show2);
        day3Show2.setBounds(640, 700, 117, 35);

        day4Show2.setText("Book");
        day4Show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day4Show2ActionPerformed(evt);
            }
        });
        getContentPane().add(day4Show2);
        day4Show2.setBounds(910, 700, 117, 35);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/Intesteller.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 130, 174, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/Joker.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 130, 174, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/oblivion.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(890, 130, 174, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/upside down.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1160, 130, 174, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/inception.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 130, 174, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/upside down.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 450, 174, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/inception.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 450, 174, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/Joker.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(890, 450, 174, 200);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/Intesteller.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1160, 450, 174, 200);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/oblivion.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 450, 174, 200);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("02.00 am");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1200, 660, 80, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("10.00 am");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(130, 350, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("10.00 am");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 350, 80, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("10.00 am");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(670, 350, 80, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("10.00 am");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(950, 350, 80, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("10.00 am");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1210, 350, 80, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("02.00 am");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(120, 670, 80, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("02.00 am");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(400, 670, 80, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("02.00 am");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(660, 670, 80, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("02.00 am");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(930, 670, 80, 20);

        jLabel11.setFont(new java.awt.Font("Academy Engraved LET", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SELECT YOUR SHOW");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 0, 700, 70);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("01/02/2020");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1190, 80, 110, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("01/02/2020");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(130, 80, 110, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("01/02/2020");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(400, 80, 110, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("01/02/2020");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(660, 80, 110, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("01/02/2020");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(920, 80, 110, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theater/app/images/1773886.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 1420, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void day1Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1Show1ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(1,movieD1S1,"01/02/2020 10.00am");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
        
    }//GEN-LAST:event_day1Show1ActionPerformed

    private void day2Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2Show1ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(2,movieD2S1,"01/02/2020 10.00am");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day2Show1ActionPerformed

    private void day5Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day5Show1ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(3,movieD5S1,"01/02/2020 10.00am");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day5Show1ActionPerformed

    private void day3Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3Show1ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(4,movieD3S1,"01/02/2020 10.00am");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day3Show1ActionPerformed

    private void day4Show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day4Show1ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(5,movieD4S1,"01/02/2020 10.00am");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day4Show1ActionPerformed

    private void day2Show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2Show2ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(6,movieD2S2,"01/02/2020 2.00pm");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day2Show2ActionPerformed

    private void day1Show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1Show2ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(2,movieD1S2,"01/02/2020 02.00pm");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day1Show2ActionPerformed

    private void day5Show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day5Show2ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(8,movieD5S2,"01/02/2020 2.00pm");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day5Show2ActionPerformed

    private void day3Show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3Show2ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(9,movieD3S2,"01/02/2020 02.00pm");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day3Show2ActionPerformed

    private void day4Show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day4Show2ActionPerformed
        // TODO add your handling code here:
        BookingPage bookingPage = new BookingPage(10,movieD4S2,"01/02/2020 2.00pm");
        bookingPage.setVisible(true);
        setVisible(false);
        bookingPage.intitial();
    }//GEN-LAST:event_day4Show2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton day1Show1;
    private javax.swing.JButton day1Show2;
    private javax.swing.JButton day2Show1;
    private javax.swing.JButton day2Show2;
    private javax.swing.JButton day3Show1;
    private javax.swing.JButton day3Show2;
    private javax.swing.JButton day4Show1;
    private javax.swing.JButton day4Show2;
    private javax.swing.JButton day5Show1;
    private javax.swing.JButton day5Show2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
